using System;
using System.Data.Entity.Infrastructure;
using DataAccessPatterns.Contracts;

namespace DataAccessPatterns.EntityFramework
{
    /// <summary>
    /// Implements <see cref="IUnitOfWork"/> over <see cref="IObjectContextAdapter"/> which is the interface implemented by database context objects generated by Entity Framework.
    /// </summary>
    public class EntityFrameworkUnitOfWork : IUnitOfWork
    {        
        public EntityFrameworkUnitOfWork(IObjectContextAdapter objectContextAdapter)
        {
            if (objectContextAdapter == null)
                throw new ArgumentNullException("objectContextAdapter");
            ObjectContextAdapter = objectContextAdapter;
        }

        protected IObjectContextAdapter ObjectContextAdapter { get; private set; }

        /// <summary>
        /// Notifies the unit of work object that the specified entity is new and should actually be added to the data store upon committing the changes.
        /// <see cref="EntityFrameworkUnitOfWork"/> implementation executes no operation, since database context objects records changes automatically itself.
        /// </summary>
        public void RegisterNew(object entity) { }

        /// <summary>
        /// Notifies the unit of work object that the specified entity is modified and should actually be updated in the data store upon committing the changes.
        /// <see cref="EntityFrameworkUnitOfWork"/> implementation executes no operation, since database context objects records changes automatically itself.
        /// </summary>
        public void RegisterDirty(object entity) { }

        /// <summary>
        /// Notifies the unit of work object that the specified entity is not modified and should be preserved as is in the data store upon committing the changes.
        /// <see cref="EntityFrameworkUnitOfWork"/> implementation executes no operation, since database context objects records changes automatically itself.
        /// </summary>
        public void RegisterClean(object entity) { }

        /// <summary>
        /// Notifies the unit of work object that the specified entity is deleted and should actually be removed from the data store upon committing the changes.
        /// <see cref="EntityFrameworkUnitOfWork"/> implementation executes no operation, since database context objects records changes automatically itself.
        /// </summary>
        public void RegisterDeleted(object entity) { }

        /// <summary>
        /// Commits changes registered on the unit of work object by performing actual insert, update, and delete operations on the data store.
        /// <see cref="EntityFrameworkUnitOfWork"/> implementation executes SaveChanges operation on the underlying database context object.
        /// </summary>
        public void Commit()
        {
            var objectContext = ObjectContextAdapter.ObjectContext;
            if (objectContext == null)
                throw new InvalidOperationException("ObjectContext is not defined, and therefore Save cannot be completed.");
            objectContext.SaveChanges();
        }

        /// <summary>
        /// Rolls back th unit of work object to its initial state.
        /// <see cref="EntityFrameworkUnitOfWork"/> implementation does not support rolling back.
        /// </summary>
        /// <exception cref="NotSupportedException"/>
        public void Rollback()
        {
            throw new NotSupportedException();
        }
    }
}
